name: Conditional Test Run

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: HTTP Request Action
        id: myRequest
        uses: fjogeleit/http-request-action@v1.10.0
        with:
          url: "https://api.us-west-1.saucelabs.com/rest/v1.2/users/oauth-abe.biswas-7996b/concurrency"
          method: "GET"
          username: ${{ secrets.SAUCE_USERNAME }}
          password: ${{ secrets.SAUCE_ACCESS_KEY }}

      - name: HTTP Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
        
      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
