name: Conditional Test Run

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: HTTP Request Action
        id: myRequest
        uses: fjogeleit/http-request-action@v1.10.0
        with:
          url: "https://api.us-west-1.saucelabs.com/rest/v1.2/users/oauth-abe.biswas-7996b/concurrency"
          method: "GET"
          username: ${{ secrets.SAUCE_USERNAME }}
          password: ${{ secrets.SAUCE_ACCESS_KEY }}

      - name: HTTP Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ fromJson(steps.myRequest.outputs.response).concurrency.organization.current.vms }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests Android in US
        if: ${{ fromJson(steps.myRequest.outputs.response).concurrency.organization.current.vms }} == 10
        run: npm run test.saucelabs.us

      - name: Run tests Android in EU
        if: ${{ fromJson(steps.myRequest.outputs.response).concurrency.organization.current.vms }} == 0
        run: npm run test.saucelabs.eu

